name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd project && docker build . --file Dockerfile --tag noumanhere/flask-blog-app:$(date +%s)
#       run: docker build ./project/. --file Dockerfile --tag noumanhere/flask-blog-app:$(date +%s)
